"""change user.password to user.hashed_password

Revision ID: 0edb07a648dc
Revises: 93f5487874e1
Create Date: 2026-02-17 12:51:51.385111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0edb07a648dc"
down_revision: Union[str, Sequence[str], None] = "93f5487874e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", new_column_name="hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "hashed_password", new_column_name="password")
    # ### end Alembic commands ###
