"""create user table and add project.owner_id

Revision ID: 93f5487874e1
Revises: 71200e88b0aa
Create Date: 2026-02-13 22:09:10.503306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f5487874e1'
down_revision: Union[str, Sequence[str], None] = '71200e88b0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'owner_id')
    # ### end Alembic commands ###
